[package]
name = "staad"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "./test_staad"]

[dependencies]
windows = { version = "0.61.3", features = [
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_Foundation",
    "Win32_System_Variant",
] }
windows-core = "0.61.2"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.98"
