use anyhow::{Result, bail};
use serde::Serialize;
use serde_json::{Value, json};
use std::sync::Arc;

use crate::openstaad::{
    app::OpenStaad, command::Command, design::Design, geometry::Geometry, load::Load,
    output::Output, property::Property, support::Support,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
pub enum Axis {
    Error = -1,
    X = 1,
    Y = 2,
    Z = 3,
    GX = 4,
    GY = 5,
    GZ = 6,
    PX = 7,
    PY = 8,
    PZ = 9,
}

impl Axis {
    pub fn as_code(&self) -> Value {
        json!(*self as i8)
    }
    pub fn as_str(&self) -> &str {
        match self {
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::GX => "GX",
            Self::GY => "GY",
            Self::GZ => "GZ",
            Self::PX => "PX",
            Self::PY => "PY",
            Self::PZ => "PZ",
            Self::Error => "ERROR",
        }
    }
    pub fn from(value: Value) -> Self {
        let n = value.as_i64().unwrap() as i8;
        match n {
            1 => Self::X,
            2 => Self::Y,
            3 => Self::Z,
            4 => Self::GX,
            5 => Self::GY,
            6 => Self::GZ,
            7 => Self::PX,
            8 => Self::PY,
            9 => Self::PZ,
            _ => Self::Error,
        }
    }
}

#[derive(Debug, Clone)]
pub enum Staad {
    OpenStaad(OpenStaad),
    Geometry(Arc<Geometry>),
    Command(Arc<Command>),
    Design(Arc<Design>),
    Load(Arc<Load>),
    Output(Arc<Output>),
    Property(Arc<Property>),
    Support(Arc<Support>),
}

unsafe impl Send for Staad {}
unsafe impl Sync for Staad {}

impl Staad {
    pub fn from_method(app: &mut Staad, method: &str) -> Result<Self> {
        let openstaad = match app {
            Self::OpenStaad(p) => p,
            _ => bail!("from_method::OpenStaad not found"),
        };
        match method {
            "Analyze"
            | "AnalyzeEx"
            | "AnalyzeModel"
            | "CloseSTAADFile"
            | "CreateNamedView"
            | "GetAnalysisStatus"
            | "GetApplicationVersion"
            | "GetBaseUnit"
            | "GetCONNECTEDProjectInfo"
            | "GetErrorMessage"
            | "GetFullJobInfo"
            | "GetInputUnitForForce"
            | "GetInputUnitForLength"
            | "GetMainWindowHandle"
            | "GetProcessHandle"
            | "GetProcessId"
            | "GetShortJobInfo"
            | "GetSTAADFile"
            | "GetSTAADFileFolder"
            | "IsAnalyzing"
            | "IsPhysicalModel"
            | "ModifyNamedView"
            | "NewSTAADFile"
            | "OpenSTAADFile"
            | "Quit"
            | "RemoveNamedView"
            | "SaveModel"
            | "SaveNamedView"
            | "SetCONNECTEDProjectInfo"
            | "SetFullJobInfo"
            | "SetInputUnitForForce"
            | "SetInputUnitForLength"
            | "SetInputUnits"
            | "SetShortJobInfo"
            | "SetSilentMode"
            | "UpdateStructure" => Ok(app.clone()),
            "DeleteAllAnalysisCommands"
            | "DeleteCheckIrregularitiesCommand"
            | "DeleteCheckSoftStoryCommand"
            | "DeleteFloorDiaphragmBaseCommand"
            | "PerformAnalysis"
            | "PerformBucklingAnalysis"
            | "PerformBucklingAnalysisEx"
            | "PerformCableAnalysis"
            | "PerformCableAnalysisEx"
            | "PerformDirectAnalysis"
            | "PerformNonlinearAnalysisEx"
            | "PerformPDeltaAnalysisEx"
            | "PerformPDeltaAnalysisNoConverge"
            | "SetCheckIrregularitiesCommand"
            | "SetCheckSoftStoryCommand"
            | "SetFloorDiaphragmBaseCommand"
            | "CreateSteelDesignCommand" => Ok(Staad::Command(openstaad.get_command()?)),
            "AssignDesignCommand"
            | "AssignDesignGroup"
            | "AssignDesignParameter"
            | "CreateDesignBrief"
            | "GetDesignBriefCode"
            | "GetMemberDesignParameters" => Ok(Staad::Design(openstaad.get_design()?)),
            "AddMultipleNodes"
            | "AddNode"
            | "CreateMultipleNodes"
            | "CreateNode"
            | "DeleteNode"
            | "GetLastNodeNo"
            | "GetNodeCoordinates"
            | "GetNodeCount"
            | "GetNodeDistance"
            | "GetNodeIncidence"
            | "GetNodeIncidence_CIS2"
            | "GetNodeList"
            | "GetNodeNumber"
            | "GetNodeUniqueId"
            | "IsOrphanNode"
            | "SetNodeCoordinate"
            | "SetNodeUniqueId"
            | "AddBeam"
            | "AddMultipleBeams"
            | "BreakBeamsAtSpecificNodes"
            | "CreateBeam"
            | "CreateMultipleBeams"
            | "DeleteBeam"
            | "GetBeamLength"
            | "GetBeamList"
            | "GetBeamsConnectedAtNode"
            | "GetCountOfBreakableBeamsAtSpecificNodes"
            | "GetIntersectBeamsCount"
            | "GetLastBeamNo"
            | "GetMemberCount"
            | "GetMemberIncidence"
            | "GetMemberIncidence_CIS2"
            | "GetMemberUniqueID"
            | "GetNoOfBeamsConnectedAtNode"
            | "IntersectBeams"
            | "IsBeam"
            | "IsColumn"
            | "IsZUp"
            | "MergeBeams"
            | "RenumberBeam"
            | "SetCheckForIdenticalEntity"
            | "SetMemberUniqueID"
            | "SplitBeam"
            | "SplitBeamInEqlParts"
            | "CreateGroupEx"
            | "DeleteGroup"
            | "GetGroupCount"
            | "GetGroupCountAll"
            | "GetGroupEntities"
            | "GetGroupEntityCount"
            | "GetGroupNames"
            | "UpdateGroup" => Ok(Staad::Geometry(openstaad.get_geometry()?)),
            "AddRSLoad"
            | "SplitLoadsOnBeam"
            | "AddWindDefinition"
            | "AddWindDefinitionASCE7Parameters"
            | "AddWindExposure"
            | "AddWindIntensity"
            | "ComputeWallWindPressureProfile"
            | "ComputeWallWindPressureProfileASCE72016"
            | "DeleteWindDefinition"
            | "AddResponseSpectrumLoadEx"
            | "AddSeismicDefinition"
            | "AddSeismicDefJointWeight"
            | "AddSeismicDefMemberWeight"
            | "AddSeismicDefSelfWeight"
            | "AddSeismicDefWallArea"
            | "ModifySeismicDefinitionParams"
            | "CreateNewReferenceLoad"
            | "GetReferenceLoadCaseCount"
            | "GetReferenceLoadCaseNumbers"
            | "SetReferenceLoadActive"
            | "AddDirectAnalysisDefinitionParameter"
            | "DeleteDirectAnalysisDefinition"
            | "DeleteDirectAnalysisDefinitionParameter"
            | "GetPrimaryLoadCaseNumbers"
            | "RemoveAttributeLoad"
            | "AddSelfWeightInXYZ"
            | "AddSelfWeightInXYZToGeometry"
            | "AddNodalLoad"
            | "AddSupportDisplacement"
            | "GetNodalLoadCount"
            | "GetNodalLoadInfo"
            | "GetNodalLoads"
            | "AddMemberAreaLoad"
            | "AddMemberConcForce"
            | "AddMemberConcMoment"
            | "AddMemberFixedEnd"
            | "AddMemberLinearVari"
            | "AddMemberTrapezoidal"
            | "AddMemberUniformForce"
            | "AddMemberUniformMoment"
            | "GetConcForceCount"
            | "GetConcForces"
            | "GetConcMomentCount"
            | "GetConcMoments"
            | "GetLinearVaryingLoadCount"
            | "GetLinearVaryingLoads"
            | "GetMemberLoadInfo"
            | "GetTrapLoadCount"
            | "GetTrapLoads"
            | "GetUDLLoadCount"
            | "GetUDLLoads"
            | "GetUNIMomentCount"
            | "GetUNIMoments"
            | "AddElementHydrostaticPressure"
            | "AddElementPressure"
            | "AddElementTrapPressureEx"
            | "GetElementConcLoadCount"
            | "GetElementConcLoads"
            | "GetElementLoadInfo"
            | "GetElementPressureLoadCount"
            | "GetElementPressureLoads"
            | "AddMemberFloorLoad"
            | "AddMemberFloorLoadEx"
            | "GetBeamCountAtFloor"
            | "GetInfluenceArea"
            | "AddStrainLoad"
            | "AddTemperatureLoad"
            | "AddSeismicLoad"
            | "IsDynamicLoadIncluded"
            | "AddWindLoad"
            | "AddNotionalLoad"
            | "AddReferenceLoad"
            | "AddRepeatLoad"
            | "BeginLoadMerging"
            | "EndLoadMerging"
            | "GetNoLoadFactorDirectionInNotionalLoad"
            | "GetNoLoadFactorInRepeatLoad"
            | "GetNoOfSetsInReferenceLoad"
            | "GetNotionalLoadByIndex"
            | "GetNotionalLoadCount"
            | "GetReferenceLoadByIndex"
            | "GetReferenceLoadCaseTitle"
            | "GetReferenceLoadCount"
            | "GetReferenceLoadType"
            | "GetRepeatLoadByIndex"
            | "GetRepeatLoadCount"
            | "AddAutoCombinationRepeat"
            | "AddAutoLoadCombinations"
            | "AddLoadAndFactorToCombination"
            | "CreateNewLoadCombination"
            | "GetLoadAndFactorForCombination"
            | "GetLoadCombinationCaseCount"
            | "GetLoadCombinationCaseNumbers"
            | "GetNoOfLoadAndFactorPairsForCombination"
            | "IsCombinationCase"
            | "ClearPrimaryLoadCase"
            | "ClearReferenceLoadCase"
            | "CreateLoadList"
            | "CreateNewPrimaryLoad"
            | "CreateNewPrimaryLoadEx"
            | "CreateNewPrimaryLoadEx2"
            | "DeleteLoadList"
            | "DeletePrimaryLoadCases"
            | "DeleteReferenceLoadCases"
            | "GetActiveLoad"
            | "GetAssignmentListForLoadType"
            | "GetAttribute"
            | "GetListSizeForLoadType"
            | "GetLoadCaseTitle"
            | "GetLoadCountInLoadList"
            | "GetLoadItemsCount"
            | "GetLoadItemType"
            | "GetLoadListCount"
            | "GetLoadsInLoadList"
            | "GetLoadType"
            | "GetLoadTypeCount"
            | "GetPrimaryLoadCaseCount"
            | "SetASDLoadAttribute"
            | "SetLoadType"
            | "SetLoadActive"
            | "SetLSDLoadAttribute"
            | "AddLoadCasesToEnvelop"
            | "CreateLoadEnvelop"
            | "DeleteLoadEnvelop"
            | "GetEnvelopeCount"
            | "GetEnvelopeIDs"
            | "GetLoadEnvelopeDetails"
            | "GetLoadListfromLoadEnvelope"
            | "RemoveLoadCasesFromEnvelop" => Ok(Staad::Load(openstaad.get_load()?)),
            "AreResultsAvailable"
            | "GetBasePressures"
            | "GetMatInfluenceAreas"
            | "GetNodeDisplacements"
            | "GetSupportReactions"
            | "GetIntermediateDeflectionAtDistance"
            | "GetIntermediateMemberAbsTransDisplacements"
            | "GetIntermediateMemberForcesAtDistance"
            | "GetIntermediateMemberTransDisplacements"
            | "GetMaxSectionDisplacement"
            | "GetMemberEndDisplacements"
            | "GetMemberEndForces"
            | "GetMinMaxAxialForce"
            | "GetMinMaxBendingMoment"
            | "GetMinMaxShearForce"
            | "GetPMemberEndForces"
            | "GetPMemberIntermediateForcesAtDistance"
            | "GetAllPlateCenterForces"
            | "GetAllPlateCenterMoments"
            | "GetAllPlateCenterPrincipalStressesAndAngles"
            | "GetAllPlateCenterPrincipalStressesAndAnglesEx"
            | "GetAllPlateCenterStressesAndMoments"
            | "GetPlateCenterNormalPrincipalStresses"
            | "GetPlateCenterVonMisesStresses"
            | "GetPlateCornerForces"
            | "GetPlateStressAtPoint"
            | "GetResultantForceAlongLineForParametricSurface"
            | "GetResultantForceAlongLineForPlateList"
            | "GetAllSolidNormalStresses"
            | "GetAllSolidPrincipalStresses"
            | "GetAllSolidShearStresses"
            | "GetAllSolidVonMisesStresses"
            | "GetMaxBeamStresses"
            | "GetMissingMassParticipationFactors"
            | "GetModalDisplacementAtNode"
            | "GetModalMassParticipationFactors"
            | "GetModeFrequency"
            | "GetNLLoadStep"
            | "GetNLNodeDisplacements"
            | "GetNoOfModesExtracted"
            | "GetTimeHistoryIntegrationStepInfo"
            | "GetTimeHistoryResponse"
            | "GetTimeHistoryResponseAtTime"
            | "GetTimeHistoryResponseMinMax"
            | "GetStaticCheckResult"
            | "GetBucklingFactor"
            | "GetBucklingModeDisplacementAtNode"
            | "GetNoOfBucklingFactors"
            | "IsBucklingAnalysisResultsAvailable"
            | "GetMemberDesignSectionName"
            | "GetMemberSteelDesignMaxFailureRatio"
            | "GetMemberSteelDesignMinFailureRatio"
            | "GetMemberSteelDesignRatio"
            | "GetMemberSteelDesignResults"
            | "GetMultipleMemberSteelDesignMaxRatio"
            | "GetMultipleMemberSteelDesignRatio"
            | "GetMultipleMemberSteelDesignResults"
            | "GetSteelDesignParameterBlockCount"
            | "GetSteelDesignParameterBlockNameByIndex"
            | "IsMultipleMemberSteelDesignResultsAvailable" => Ok(Staad::Output(openstaad.get_output()?)),
            "CreateAnglePropertyFromTable"
            | "CreateBeamPropertyFromTable"
            | "CreateBeamPropertyFromTableComposite"
            | "CreateBeamPropertyFromTableEx"
            | "CreateBeamPropertyFromTableWithCoverPlates"
            | "CreateChannelPropertyFromTable"
            | "CreatePipePropertyFromTable"
            | "CreatePlateThicknessProperty"
            | "CreatePrismaticCircleProperty"
            | "CreatePrismaticGeneralProperty"
            | "CreatePrismaticRectangleProperty"
            | "CreatePrismaticTeeProperty"
            | "CreatePrismaticTrapezoidalProperty"
            | "CreateTaperedIProperty"
            | "CreateTaperedTubeProperty"
            | "CreateTeePropertyFromTable"
            | "CreateTubePropertyFromTable"
            | "CreateWideFlangePropertyFromTable"
            | "AddUPTPropertyANGLE"
            | "AddUPTPropertyCHANNEL"
            | "AddUPTPropertyDOUBLEANGLE"
            | "AddUPTPropertyGENERAL"
            | "AddUPTPropertyISECTION"
            | "AddUPTPropertyPIPE"
            | "AddUPTPropertyPRISMATIC"
            | "AddUPTPropertyTEE"
            | "AddUPTPropertyTUBE"
            | "AddUPTPropertyWIDEFLANGE"
            | "AddUPTPropertyWIDEFLANGECOMPOSITE"
            | "AddUPTPropertyWIDEFLANGEUNEQUAL"
            | "CreatePropertyFromUPTTable"
            | "CreateUPTTable"
            | "GetUptGeneralProfileBoundaryPoints"
            | "GetUptGeneralProfilePointsCount"
            | "GetUptGeneralStressLocationPoints"
            | "AssignBetaAngle"
            | "GetBetaAngle"
            | "GetBeamSectionDisplayName"
            | "GetBeamSectionName"
            | "GetBeamSectionPropertyRefNo"
            | "GetBeamSectionPropertyTypeNo"
            | "GetBeamSectionPropertyValuesEx"
            | "GetCountofSectionPropertyValuesEx"
            | "GetCountryTableNo"
            | "GetIsotropicMaterialAssignedPlateList"
            | "GetPlateThickness"
            | "GetRecordForSection"
            | "GetSectionPropertyAssignedBeamCount"
            | "GetSectionPropertyAssignedBeamList"
            | "GetSectionPropertyCount"
            | "GetSectionPropertyCountry"
            | "GetSectionPropertyList"
            | "GetSectionPropertyName"
            | "GetSectionPropertyType"
            | "GetSectionPropertyValues"
            | "GetSectionPropertyValuesEx"
            | "GetSectionTableNo"
            | "GetShapeCode"
            | "GetThicknessPropertyAssignedPlateCount"
            | "GetThicknessPropertyAssignedPlateList"
            | "GetThicknessPropertyCount"
            | "GetThicknessPropertyList"
            | "GetThicknessPropertyValues"
            | "RemoveMaterialFromPlate"
            | "RemoveMaterialFromSolid"
            | "RemovePropertyFromPlate"
            | "CreatePropertyFromUserTable"
            | "CreateUPTTableEx"
            | "FindUPTTable"
            | "GetUserProvidedTableCount"
            | "GetUserProvidedTableList"
            | "GetUserProvidedTableNo"
            | "GetUserProvidedTableSectionCount"
            | "GetUserProvidedTableSectionList"
            | "GetUserProvidedTableSectionProperties"
            | "GetUserProvidedTableSectionPropertyCount"
            | "GetUserProvidedTableSectionType"
            | "RemovePropertyFromUPTTable"
            | "RemoveUPTTable"
            | "AddControlDependentRelation"
            | "CreateElementIgnoreInplaneRotnSpec"
            | "CreateElementLocalZOffsetSpec"
            | "CreateElementNodeReleaseSpec"
            | "CreateElementOffsetSpec"
            | "CreateElementPlaneStressSpec"
            | "CreateMemberCableSpec"
            | "CreateMemberCableSpecEx"
            | "CreateMemberCompressionSpec"
            | "CreateMemberFireProofingSpec"
            | "CreateMemberIgnoreStiffSpec"
            | "CreateMemberInactiveSpec"
            | "CreateMemberOffsetSpec"
            | "CreateMemberPartialReleaseSpec"
            | "CreateMemberReleaseSpec"
            | "CreateMemberTensionSpec"
            | "CreateMemberTrussSpec"
            | "DeleteAllControlDependentRelations"
            | "DeleteMemberReleaseSpec"
            | "DeleteMemberSpec"
            | "DeleteProperty"
            | "GetAlphaAngleForSection"
            | "GetCentroidLocationForSection"
            | "GetElementOffsetSpecCount"
            | "GetFireProofDataForBeam"
            | "GetFireProofedBeamCount"
            | "GetFireProofedBeamList"
            | "GetFireProofingSpecAssignedBeamCount"
            | "GetFireProofingSpecAssignedBeamList"
            | "GetFireProofingSpecCount"
            | "GetFireProofingSpecDetails"
            | "GetInactiveMemberCount"
            | "GetInactiveMemberList"
            | "GetMemberReleaseSpecEx"
            | "GetMemberSpecCode"
            | "GetPropertyUniqueID"
            | "RemoveAllElementNodeReleaseSpec"
            | "RemoveAllElementOffsetSpec"
            | "RemoveBeamPropertyHelper"
            | "RemoveElementIgnoreInplaneRotnSpecFromPlate"
            | "RemoveElementNodeReleaseSpecFromPlate"
            | "RemoveElementPlaneStressSpecFromPlate"
            | "RemoveMemberCableSpecFromBeam"
            | "RemoveMemberCompressionSpecFromBeam"
            | "RemoveMemberFireProofingSpecFromBeam"
            | "RemoveMemberIgnoreStiffSpecFromBeam"
            | "RemoveMemberInactiveSpecFromBeam"
            | "RemoveMemberOffsetSpecFromBeam"
            | "RemoveMemberReleaseSpecFromBeam"
            | "RemoveMemberTensionSpecFromBeam"
            | "RemoveMemberTrussSpecFromBeam"
            | "RemovePropertyFromBeam"
            | "SetPropertyUniqueID"
            | "AssignBeamProperty"
            | "AssignElementSpecToPlate"
            | "AssignMemberSpecToBeam"
            | "AssignPlateThickness"
            | "CreateAssignProfileProperty"
            | "UpdatePropertiesToDesignSection"
            | "CreateIsotropicMaterialAluminum"
            | "CreateIsotropicMaterialConcrete"
            | "CreateIsotropicMaterialProperties"
            | "CreateIsotropicMaterialPropertiesEx"
            | "CreateIsotropicMaterialSteel"
            | "CreateIsotropicMaterialTimber"
            | "DeleteMaterial"
            | "GetBeamMaterialName"
            | "GetElementMaterialName"
            | "GetIsotropicMaterialAssignedBeamCount"
            | "GetIsotropicMaterialAssignedBeamList"
            | "GetIsotropicMaterialAssignedPlateCount"
            | "GetIsotropicMaterialAssignedSolidCount"
            | "GetIsotropicMaterialAssignedSolidList"
            | "GetIsotropicMaterialCount"
            | "GetIsotropicMaterialProperties"
            | "GetIsotropicMaterialPropertiesAssigned"
            | "GetIsotropicMaterialPropertiesEx"
            | "GetMaterialProperty"
            | "GetMaterialPropertyEx"
            | "GetOrthotropic2DMaterialCount"
            | "GetOrthotropic2DMaterialProperties"
            | "GetOrthotropic3DMaterialCount"
            | "GetOrthotropic3DMaterialProperties"
            | "GetPlateMaterialName"
            | "GetSolidMaterialName"
            | "GetTypeForIsotropicMaterial"
            | "RemoveBeamMaterialHelper"
            | "RemoveMaterialFromBeam"
            | "SetTypeToIsotropicMaterial"
            | "AssignMaterialToMember"
            | "AssignMaterialToPlate"
            | "AssignMaterialToSolid"
            | "SetMaterialID"
            | "SetMaterialName"
            | "CreateElementAttribute"
            | "CreateMemberAttribute"
            | "DeleteElementAttribute"
            | "DeleteMemberAttribute"
            | "GetAssignedAttributeByIndex"
            | "GetAssignedAttributeCount"
            | "GetElementCountByAttribute"
            | "GetElementListByAttribute"
            | "GetMemberAttributeCount"
            | "GetMemberAttributeList"
            | "GetMemberCountByAttribute"
            | "GetMemberListByAttribute"
            | "RemoveAttributeProperty"
            | "AssignElementAttribute"
            | "AssignMemberAttribute"
            | "GetBeamConstants"
            | "GetBeamProperty"
            | "GetBeamPropertyAll"
            | "GetElementGlobalOffset"
            | "GetElementLocalOffset"
            | "GetElementOffsetSpec"
            | "GetMemberGlobalOffSet"
            | "GetMemberLocalOffSet"
            | "GetMemberReleaseSpec"
            | "GetPlateSectionPropertyRefNo"
            | "GetPublishedProfileName"
            | "GetSTAADProfileName"
            | "GetDefaultStandardProfileDBFolder"
            | "GetStandardProfileDBFolder"
            | "GetStandardSectionDatabaseName"
            | "GetStandardSectionName"
            | "GetStandardSectionTableName"
            | "IsStandardDatabaseSection"
            | "SetStandardProfileDBFolder" => Ok(Staad::Property(openstaad.get_property()?)),
            "AssignSupportToEntityList"
            | "AssignSupportToNode"
            | "CreateElasticFooting"
            | "CreateElasticMat"
            | "CreateInclinedSupport"
            | "CreatePlateMat"
            | "CreateSupportFixed"
            | "CreateSupportFixedBut"
            | "CreateSupportPinned"
            | "CreateSupportSpring"
            | "DeleteSupport"
            | "GetSupportName"
            | "GetSupportUniqueID"
            | "RemoveSupportFromAllNodes"
            | "RemoveSupportFromEntityList"
            | "RemoveSupportFromNode"
            | "GetCountOfElasticFooting"
            | "GetCountOfElasticMat"
            | "GetCountOfPlateMat"
            | "GetElasticFootingAssignmentList"
            | "GetElasticFootingDetail"
            | "GetElasticMatAssignmentList"
            | "GetElasticMatDetail"
            | "GetPlateMatAssignmentList"
            | "GetPlateMatDetail"
            | "GetPlateMatSupportId"
            | "GetSupportCount"
            | "GetSupportInformation"
            | "GetSupportInformationEx"
            | "GetSupportNodes"
            | "GetSupportType" => Ok(Staad::Support(openstaad.get_support()?)),
            _ => bail!("There is no parent instance for '{}' method", method),
        }
    }
}
